

HMI_CMD_TOPIC: "/hmi/cmd"

# Raw point cloud data 
PRE_SCAN_TOPIC: "/pre_scan_0"
POST_SCAN_TOPIC: "/post_scan_0"

# Preprocess point cloud data
PRE_SCAN_CLOUD_TOPIC: "/pre_scan_cloud"
POST_SCAN_CLOUD_TOPIC: "/post_scan_cloud"

# Cloud after compare between Pres can and Post scan point cloud
CLOUD_COMPARED_TOPIC: "/cloud_compared"

ENCODER_JOINT_NAME: "scanner_deploy_retract"

# Start Housing possition in degree (start to collect data)
HOUSING_START_POSITION : 15 # value in degree (not in radian)
HOUSING_END_POSITION : 90 # value in degree (not in radian)